### ISSUE TITLE
Broker permission error

### ISSUE THREAD

**Issue by mattfarina** [osbkit/minibroker#1]
I got the error:

```
controller.go:293] error getting the cluster info configmap: "configmaps \"cluster-info\" is forbidden: User \"system:serviceaccount:svc-cat:service-catalog-controller-manager\" cannot get configmaps in the namespace \"default\""
```

The `service-catalog-controller-manager` didn't have permission. It was causing a `ErrorFetchingCatalog` error.

I fixed it, for the moment, by giving the service account:

```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
```

I didn't get this in other environments I've run the catalog in.

Disclaimer, I read the warning "This is still a work-in-progress, it's not usable yet." but I wanted to try anyway. Figured I'd pass this on.
